name: Java CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [17, 21]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
    
    - name: Run tests
      run: ./gradlew test --no-daemon
    
    - name: Generate test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Gradle Tests
        path: build/test-results/test/*.xml
        reporter: java-junit
    
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: jar-file-java-${{ matrix.java-version }}
        path: build/libs/*.jar
        retention-days: 7
    
    - name: Check code coverage
      if: matrix.java-version == '17'
      run: ./gradlew jacocoTestReport
    
    - name: Upload coverage to Codecov
      if: matrix.java-version == '17'
      uses: codecov/codecov-action@v4
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: false
